spring.application.name=ecom-order
spring.sql.init.mode=always
spring.main.web-application-type=reactive
spring.r2dbc.url=r2dbc:h2:mem:///ecom-order;MODE=MySQL
spring.r2dbc.username=sa
spring.r2dbc.password=

springdoc.swagger-ui.path=/apispec.html
springdoc.swagger-ui.url=/apispec.yaml
springdoc.api-docs.enabled=true

logging.level.org.springframework.r2dbc=DEBUG

spring.messages.encoding=UTF-8

jasypt.encryptor.password=${ENCRYPTION_KEY}
jasypt.encryptor.algorithm=PBEWithHMACSHA512AndAES_256
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
jasypt.encryptor.key-obtention-iterations=1000

token.jwt.secret=ENC(RFTbdDKIF/+kFhFZ2sKkwiC586suCuty6dZVKzggKtzQPwR6k02q6jFUKPQG35+a7l2dIJA8jQfr95OkMVYdfg==)

# WebClient 설정 값
app.member-api.url=https://api.partner-member.com
app.member-api.pool-size=100
app.member-api.pool-acquire-time=3
app.member-api.pool-idle-time=30
app.member-api.pool-max-time=60
app.member-api.pool-evict-time=30
app.member-api.time-out=3

app.product-api.url=https://api.partner-product.com
app.product-api.pool-size=100
app.product-api.pool-acquire-time=3
app.product-api.pool-idle-time=30
app.product-api.pool-max-time=60
app.product-api.pool-evict-time=30
app.product-api.time-out=3

app.stock-api.url=https://api.partner-stock.com
app.stock-api.pool-size=100
app.stock-api.pool-acquire-time=3
app.stock-api.pool-idle-time=30
app.stock-api.pool-max-time=60
app.stock-api.pool-evict-time=30
app.stock-api.time-out=3


